In [25]:
import numpy as np
import pandas as pd

In [26]:
!pip install kaggle

Requirement already satisfied: kaggle in d:\new folder\lib\site-packages (2.0.0)
Requirement already satisfied: bleach in d:\new folder\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in d:\new folder\lib\site-packages (from kaggle) (0.1.16)
Requirement already satisfied: packaging in d:\new folder\lib\site-packages (from kaggle) (24.2)
Requirement already satisfied: protobuf in d:\new folder\lib\site-packages (from kaggle) (6.32.1)
Requirement already satisfied: python-dateutil in d:\new folder\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in d:\new folder\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in d:\new folder\lib\site-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in d:\new folder\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in d:\new folder\lib\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in d:\new folder\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in d:\new folder\lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in d:\new folder\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\new folder\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\new folder\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in d:\new folder\lib\site-packages (from requests->kaggle) (2025.8.3)
Requirement already satisfied: colorama in c:\users\devul\appdata\roaming\python\python313\site-packages (from tqdm->kaggle) (0.4.6)

In [27]:
!kaggle datasets download -d fredericobreno/play-tennis

Dataset URL: https://www.kaggle.com/datasets/fredericobreno/play-tennis
License(s): unknown
play-tennis.zip: Skipping, found more recently modified local copy (use --force to force download)

In [28]:
import zipfile

with zipfile.ZipFile("play-tennis.zip", "r") as zip_ref:
    zip_ref.extractall()

In [29]:
import pandas as pd

df = pd.read_csv("play_tennis.csv")
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [30]:
df=df.drop("day",axis=1)
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

# problem 1 
# outlook=sunny,temp=Hot,humidity=high,wind=weak
#play or no play

sol
p(yes|sunny,hot,high,weak)=p(sunny|yes)*p(hot|yes)*p(high|yes)*p(weak|yes)*p(yes)
and
p(no|sunny,hot,high,weak)=p(sunny|no)*p(hot|no)*p(high|no)*p(weak|no)*p(no)

compare both and select the maximum one

In [31]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [32]:
py=9/13
pn=5/13
print(py)
print(pn)

0.6923076923076923
0.38461538461538464

In [33]:
#outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [34]:
psy=2/9
psn=3/5

pry=3/9
prn=2/5

poy=4/9
pon=0

In [35]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [36]:
pcy=3/9
pcn=1/5

photy=2/9
photn=2/5

pmy=4/9
pmn=2/5

In [37]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [38]:
phighy=3/9
phighn=4/5

pny=6/9
pnn=1/5

In [39]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [40]:
psy=3/9
psn=3/5

pwy=6/9
pwn=2/5

In [43]:
pyes=psy*photy*phighy*pwy*py
pno=psn*photy*phighy*pwn*pn
print(pyes)
print(pno)

0.011396011396011395
0.006837606837606838

so play 👍